Constants
WiktoriaKrzyzanska/pio_git_rhymers pull request #2
Opened 2023-04-18 19:50 UTC by brzezin0

2023-04-18 21:51 UTC, WiktoriaKrzyzanska commented
6. Brakuje zmiany w IntLinkedList

2023-04-18 21:53 UTC, WiktoriaKrzyzanska commented
7 i 8 nie mają błędów

2023-04-19 08:47 UTC, WiktoriaKrzyzanska requested changes

2023-04-19 08:47 UTC, WiktoriaKrzyzanska commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public static final int MAX_CAPACITY = 11;
Nie można używać MAX i CAPACITY

2023-04-19 08:57 UTC, WiktoriaKrzyzanska requested changes

2023-04-19 08:57 UTC, WiktoriaKrzyzanska commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public static final int EMPTY = -1;
Brakuje drugiego -1. Mają być dwie różne wartości dla -1

2023-04-19 09:08 UTC, WiktoriaKrzyzanska requested changes

2023-04-19 09:08 UTC, WiktoriaKrzyzanska commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +        return total == MAX_CAPACITY;
Wartość MAX_CAPACITY 11 powinna być zależna od wartości SIZE, czyli powinno to być na zasadzie SIZE-1

2023-04-19 09:20 UTC, WiktoriaKrzyzanska requested changes

2023-04-19 09:20 UTC, WiktoriaKrzyzanska commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public static final int VALUE_START = -1;
sens stałej dotyczącej domyślnej zwracanej wartości można określić za pomocą słów, np. IF_EMPTY lub DEFAULT, RETURN, VALUE (np. DEFAULT_VALUE).

2023-04-19 09:31 UTC, WiktoriaKrzyzanska requested changes

2023-04-19 09:31 UTC, WiktoriaKrzyzanska commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
>      public static final int SIZE = 12;
Nie może być SIZE

2023-04-19 09:31 UTC, brzezin0 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
>      public static final int SIZE = 12;
ok

2023-04-25 13:25 UTC, merged